/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package adboswing.boudaries;

import adboswing.entities.Connexion;
import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Malcolm
 */
public class NewJInternaStatut extends javax.swing.JInternalFrame {

    // déclaration de des variriables
    Connection DbConect;
    ResultSet irslt;
    Statement stmt;
    int iiPosition = 1;
    int iiCount;
    String lsSelect = "SELECT * FROM statut";

    /**
     * Creates new form NewJInternalFrame
     */
    public NewJInternaStatut() throws SQLException {
        initComponents();
        
         //this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(64, 159, 170));

        // connection a la base de donnée
         DbConect = Connexion.getConnexion();
        try {
//            Class.forName("org.gjt.mm.mysql.Driver");
//            DbConect = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/journal2014", "root", "");
//            DbConect.setAutoCommit(false);

            // statement
            stmt = DbConect.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            // la requette
            irslt = stmt.executeQuery(lsSelect);
            irslt.last(); // je vais au dernier enregistrements
            iiCount = irslt.getRow();// recupere le numero d'enregisment en cour
            irslt.first();// repositionnement sur le premier enregistrement
            afficheEnregistrement();

        } catch (Exception e) {
            System.out.println("Erreur connexion : " + e.getMessage());

            // --- Les boutons Actifs || Inactifs
            /// Boucle pour griser les boutton quand on a la 1ere ligne et a la dernier ligne
            //si les 2 premier boutton sont = 1 sont desactiver
//        if ( rslt.isFirst()){
//            jButtonFirst.setEnabled(false);
//            jButtonPrevious.setEnabled(false);
//           // sinon ils sont activer parce que on peut encore aller a l'arriere.
//        }else{
//            jButtonFirst.setEnabled(true);
//            jButtonPrevious.setEnabled(true);
//        }// si on est a la derniere ligne de lecture de mon doc les deux suivant doit entre desativer
//        
//        //parce qu'on ne peut plus aller plus loins
//        if ( rslt.isLast() ){
//            jButtonNext.setEnabled(false);
//            jButtonLast.setEnabled(false);
//           
//        }else{// sinon  s'il y a possibileté d'aller plus loin ils sont activer
//            jButtonNext.setEnabled(true);
//            jButtonLast.setEnabled(true);
//        }
        }
    }
// un fonction deffini pour affiche les champs, on vas l appeler partour on voudras afficher.

    private void afficheEnregistrement() throws SQLException {
        jTextFieldID.setText(irslt.getString("id_statut"));
        jTextFieldStatut.setText(irslt.getString("statut"));
        jTextFieldAbreviation.setText(irslt.getString("abreviation_statut"));

        this.jButtonFirst.setEnabled(!irslt.isFirst());
        this.jButtonPrevious.setEnabled(!irslt.isFirst());

        this.jButtonNext.setEnabled(!irslt.isLast());
        this.jButtonLast.setEnabled(!irslt.isLast());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelID = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabelStatut = new javax.swing.JLabel();
        jTextFieldStatut = new javax.swing.JTextField();
        jLabelAbreviation = new javax.swing.JLabel();
        jTextFieldAbreviation = new javax.swing.JTextField();
        jButtonFirst = new javax.swing.JButton();
        jButtonPrevious = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jButtonLast = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonAjouter = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonSubmit = new javax.swing.JButton();
        jLabelCompteur = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Statut");
        setToolTipText("");

        jLabelID.setText("ID");

        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        jLabelStatut.setText("Statut");

        jLabelAbreviation.setText("Abréviation");

        jButtonFirst.setText("<<");
        jButtonFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFirstActionPerformed(evt);
            }
        });

        jButtonPrevious.setText("<");
        jButtonPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviousActionPerformed(evt);
            }
        });

        jButtonNext.setText(">");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jButtonLast.setText(">>");
        jButtonLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLastActionPerformed(evt);
            }
        });

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        jButtonSupprimer.setText("Spprimer");
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Modifier");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Annuler");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonSubmit.setText("Valider");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        jLabelCompteur.setText("Compteur:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelStatut)
                                .addComponent(jButtonClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonFirst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelAbreviation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(54, 54, 54)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButtonAjouter)
                                        .addComponent(jButtonPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonNext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonSupprimer, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(60, 60, 60)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonLast, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonUpdate)))
                                .addComponent(jTextFieldID)
                                .addComponent(jTextFieldStatut)
                                .addComponent(jTextFieldAbreviation)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelCompteur))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelID)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatut)
                    .addComponent(jTextFieldStatut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAbreviation)
                    .addComponent(jTextFieldAbreviation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFirst)
                    .addComponent(jButtonPrevious)
                    .addComponent(jButtonNext)
                    .addComponent(jButtonLast))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonAjouter)
                    .addComponent(jButtonSupprimer)
                    .addComponent(jButtonUpdate))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSubmit)
                    .addComponent(jButtonCancel))
                .addGap(18, 18, 18)
                .addComponent(jLabelCompteur)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        try {
            // TODO add your handling code here:
            DbConect.rollback();
        } catch (SQLException ex) {
            Logger.getLogger(NewJInternaStatut.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
        // un try pour activer les boutton et appelle ma fonction en meme temps ( afficheEnregistrement.
        try {
            irslt.next();
            afficheEnregistrement();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousActionPerformed
        // TODO add your handling code here:
        try {
            irslt.previous();
            afficheEnregistrement();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonPreviousActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        // pour clear les champs
        jTextFieldID.setText("");
        jTextFieldStatut.setText("");
        jTextFieldAbreviation.setText("");

    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        try {
            // pour clear les champs
            irslt.moveToInsertRow();// aller ver le BD
            irslt.updateString("statut", jTextFieldStatut.getText());
            irslt.updateString("abreviation_statut", jTextFieldAbreviation.getText());
            irslt.insertRow();
        } catch (SQLException ex) {
            Logger.getLogger(NewJInternaStatut.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jButtonFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFirstActionPerformed
        // TODO add your handling code here:
        try {
            irslt.first();
            afficheEnregistrement();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonFirstActionPerformed

    private void jButtonLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLastActionPerformed
        // TODO add your handling code here:
        try {
            irslt.last();
            afficheEnregistrement();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonLastActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        try {
            // TODO add your handling code here:
            // pour modifier 
            irslt.updateString("statut", jTextFieldStatut.getText());
            irslt.updateString("abreviation_statut", jTextFieldAbreviation.getText());
            irslt.updateRow();
        } catch (SQLException ex) {
            Logger.getLogger(NewJInternaStatut.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        try {
            // TODO add your handling code here:

            DbConect.commit();
            afficheEnregistrement();
        } catch (SQLException ex) {
            Logger.getLogger(NewJInternaStatut.class.getName()).log(Level.SEVERE, null, ex);

        }
        // this.jLabelCompteur.setText((iiPosition = 1) + "/" + iiCount);
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
         this.jTextFieldID.setEnabled(false);
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
        // TODO add your handling code here:
        try {
             irslt.deleteRow();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonSupprimerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonFirst;
    private javax.swing.JButton jButtonLast;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabelAbreviation;
    private javax.swing.JLabel jLabelCompteur;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelStatut;
    private javax.swing.JTextField jTextFieldAbreviation;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldStatut;
    // End of variables declaration//GEN-END:variables
}
